# Backend API service configuration example
# Override with: helm template -f deploy/values.backend.yaml

teamName: "naqliyat"

service:
  name: "backend"
  port: 80
  type: ClusterIP

image:
  registry: "060795935816.dkr.ecr.ap-southeast-1.amazonaws.com"
  repository: ""
  tag: ""
  pullPolicy: IfNotPresent

containerPort: 80

replicaCount: 1

resources:
  requests:
    memory: "1024Mi"
    cpu: "1100m"


ingress:
  enabled: true
  className: "alb"
  hostname: ""
  
  healthCheck:
    path: "/"
    intervalSeconds: 15
    timeoutSeconds: 5
    healthyThreshold: 2
    unhealthyThreshold: 2
    successCodes: "200,404"

env: []
  # - name: PORT
  #   value: "3000"
  # - name: NODE_ENV
  #   value: "production"

# envFromSecrets:
#   - secretName: "app-secrets"

# envFromConfigMaps:
#   - configMapName: "app-config"

livenessProbe:
  enabled: true
  httpGet:
    path: /health
    port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  enabled: true
  httpGet:
    path: /health
    port: 3000
  initialDelaySeconds: 5
  periodSeconds: 5

persistence:
  enabled: false


mssql:
  enabled: true

  global:
    storageClass: "managed-csi-premium" # Change this if needed

  auth:
    database: naqliyat
    rootPassword: 'YourStrong@Passw0rd'
    username: sa
    password: 'YourStrong@Passw0rd'